/**
 * Email Service - Send documents via Gmail
 */

import nodemailer from 'nodemailer';

interface EmailOptions {
  to: string;
  subject: string;
  text: string;
  html?: string;
  attachments?: Array<{
    filename: string;
    content: Buffer | string;
    contentType?: string;
  }>;
}

class EmailService {
  private transporter: any;

  constructor() {
    // Note: In production, use environment variables for credentials
    // For now, we'll create a transporter that can be configured
    this.initializeTransporter();
  }

  private initializeTransporter() {
    const gmailUser = process.env.GMAIL_USER;
    const gmailAppPassword = process.env.GMAIL_APP_PASSWORD;

    if (gmailUser && gmailAppPassword) {
      this.transporter = nodemailer.createTransport({
        service: 'gmail',
        auth: {
          user: gmailUser,
          pass: gmailAppPassword, // App-specific password
        },
      });
      console.log('📧 Email service initialized');
    } else {
      console.log('⚠️  Email service not configured (set GMAIL_USER and GMAIL_APP_PASSWORD)');
    }
  }

  async sendEmail(options: EmailOptions): Promise<boolean> {
    if (!this.transporter) {
      console.error('Email service not configured');
      return false;
    }

    try {
      const info = await this.transporter.sendMail({
        from: process.env.GMAIL_USER,
        to: options.to,
        subject: options.subject,
        text: options.text,
        html: options.html || options.text.replace(/\n/g, '<br>'),
        attachments: options.attachments,
      });

      console.log(`✅ Email sent: ${info.messageId}`);
      return true;
    } catch (error) {
      console.error('Email send error:', error);
      return false;
    }
  }

  async sendDocumentEmail(
    recipientEmail: string,
    documentTitle: string,
    documentBuffer: Buffer,
    documentType: string
  ): Promise<boolean> {
    const extension = documentType === 'invoice' ? 'png' : 'png';
    
    return this.sendEmail({
      to: recipientEmail,
      subject: `Document: ${documentTitle}`,
      text: `Please find attached: ${documentTitle}\n\nGenerated by SafeDoc`,
      html: `
        <div style="font-family: Arial, sans-serif; padding: 20px;">
          <h2 style="color: #6366F1;">📄 Document Delivery</h2>
          <p>Please find your document attached:</p>
          <p><strong>${documentTitle}</strong></p>
          <hr style="border: 1px solid #E5E7EB; margin: 20px 0;">
          <p style="color: #6B7280; font-size: 14px;">
            This document was generated by SafeDoc<br>
            Generated on ${new Date().toLocaleString()}
          </p>
        </div>
      `,
      attachments: [
        {
          filename: `${documentTitle}.${extension}`,
          content: documentBuffer,
          contentType: `image/${extension}`,
        },
      ],
    });
  }

  isConfigured(): boolean {
    return !!this.transporter;
  }
}

export default EmailService;
